### PR TITLE
Partial support for GNURadio 3.8

### PR DESCRIPTION
**Pull request by hj1980**
Initial working version for GNURadio v3.8. Currently supporting a single channel only. #44 #37

### CODE REVIEW

**Comment by hj1980** [comment]
This currently builds and runs as a single channel source on Arch. (from gnuradio commit 943f3c194) 
It was essentially created from scratch using gr_modtool, code copied over from prior and then yaml hand made. I'm currently unsure about the actual requirement for boost.

**Comment by oidaRUNG** [comment]
> This currently builds and runs as a single channel source on Arch. (from gnuradio commit 943f3c194)
> It was essentially created from scratch using gr_modtool, code copied over from prior and then yaml hand made. I'm currently unsure about the actual requirement for boost.

installing this now. There are no limitations on that single Rx channel?

**Comment by hj1980** [comment]
> > This currently builds and runs as a single channel source on Arch. (from gnuradio commit 943f3c194)
> > It was essentially created from scratch using gr_modtool, code copied over from prior and then yaml hand made. I'm currently unsure about the actual requirement for boost.
> 
> installing this now. There are no limitations on that single Rx channel?

Not that I have found (compared to previous version). Let me know how it goes for you.

**Comment by oidaRUNG** [comment]
> > > This currently builds and runs as a single channel source on Arch. (from gnuradio commit 943f3c194)
> > > It was essentially created from scratch using gr_modtool, code copied over from prior and then yaml hand made. I'm currently unsure about the actual requirement for boost.
> > 
> > 
> > installing this now. There are no limitations on that single Rx channel?
> 
> Not that I have found (compared to previous version). Let me know how it goes for you.

So I have just build gnuradio from source from the master branch seeing as the commit(943f3c194) has been merged. This gives me gnuradio 3.9.

This blocks your cmake build seeing as it wants 3.8.
Changing that required gnuradio version fixes it.

Afterwards the build went fine.

What software have you used exactly to test it out? Any compatibilty with gqrx? Or have a simple gnuradio example? Only got it a few days ago and it's been a bit of a struggle getting it to work.

Completely different than a rtl-sdr which was just plug and play.

**Comment by hj1980** [comment]
> > > > This currently builds and runs as a single channel source on Arch. (from gnuradio commit 943f3c194)
> > > > It was essentially created from scratch using gr_modtool, code copied over from prior and then yaml hand made. I'm currently unsure about the actual requirement for boost.
> > > 
> > > 
> > > installing this now. There are no limitations on that single Rx channel?
> > 
> > 
> > Not that I have found (compared to previous version). Let me know how it goes for you.
> 
> So I have just build gnuradio from source from the master branch seeing as the commit(943f3c194) has been merged. This gives me gnuradio 3.9.
> 
> This blocks your cmake build seeing as it wants 3.8.
> Changing that required gnuradio version fixes it.
> 
> Afterwards the build went fine.
> 
> What software have you used exactly to test it out? Any compatibilty with gqrx? Or have a simple gnuradio example? Only got it a few days ago and it's been a bit of a struggle getting it to work.
> 
> Completely different than a rtl-sdr which was just plug and play.

Cheers - I'll have to fix the version.

Take a look at this:
https://gist.github.com/hj1980/7d80bb198eb613767ba30727374edb87

Just need to tune it to your favourite FM station.

**Pull request merged**
